<?php
/**
 * HTML calculate_cep
 * 
 * @author      MarioSAM <eu@mariosam.com.br>
 * @version     1.0.0
 * @date        2021/01
 * @copyright   Blog do Mario SAM
 * 
 * This page control how the estimate CEP price will be displayed.
 */

/** inicializando model e variaveis */
if ( $this->getEnabled() ) {
//nao carregar pagina se o produto for virtual ou digital
if ( 'downloadable' != $this->getProductType() && 'virtual' != $this->getProductType() ) {

$_proPrice = $this->getProductPrice();
$_proWeight = $this->getProductWeight();

$_cepOrigin = $this->getCepOrigin();
$_position = $this->getCepPosition();
$_cepModes = $this->getCepModes();
$_cepEmpresa = $this->getCepEmpresa();
$_cepPass = $this->getCepSenha();
$_cepComprimento = $this->getCepComprimento();
$_cepDiametro = $this->getCepDiametro();
$_cepAltura = $this->getCepAltura();
$_cepLargura = $this->getCepLargura();
$_cepFormato = $this->getCepFormato();

$_cepFree = $this->getCepFree();
$_cepFreePrice = $this->getCepFreeOverPrice();
$_cepFreeDays = $this->getCepFreeDays();
?>
<?php /* CSS styles */ ?>
<style type="text/css">
#calc_cep { display: inline-block; min-width: 350px; }
#calc_cep label { font-weight: bold; }
#cep { width: 100px; margin: 0px 0px 0px 10px; }
#res_frete { background: #fafbfd; padding: 10px 5px 10px 15px; margin: 0px 0px 10px 0px; }
#cep-button { vertical-align: top; }

.ocultar { display: none; }
.exibir { display: block; }

.tocep {}
.tipo { font-weight: bold; display: inline-block; width: 30%; }
.prazo { display: inline-block; width: 20%; }
.valor { font-weight: bold; text-align: right; }

<?php echo $this->getCssCustomCalculateCep(); ?>
</style>

<?php /* Javascript controls */ ?>
<script type="text/javascript">
//<![CDATA[
document.observe("dom:loaded", function() {
    <?php /* falta inserir a mascara no campo e validar cep com mask */ ?>
    //$("cep").mask("99999-999");
    <?php /* insere o box de calculo de frete dinamicamente na pagina */ ?>
    var dTip = '<?php echo $_position; ?>';
    var pDiv = dTip.substring(1);
    if ( dTip.startsWith('#') ) {
        document.getElementById( pDiv ).appendChild( $("calc_cep") );
    } else {
        document.getElementsByClassName( pDiv )[0].appendChild( $("calc_cep") );
    }

    <?php /* controla as mensagens de validacao e retorno do calculo de frete */ ?>
    function showMsgCep( msg ) {
        $('res_frete').classList.remove('ocultar');
        $('res_frete').update( msg );
    }

    <?php /* pre-chamada para validar o campo cep */ ?>
    function beforeCalcep( cep ) {
        cep = cep.replace(/\D/g, '');
        var validacep = /^[0-9]{8}$/; //Expressão regular para validar o CEP.

        <?php /* Valida o formato do CEP. */ ?>
        if ( validacep.test( cep ) && cep.length > 5 ) {
            calcep( cep ); //chama funcao ajax
        } else {
            showMsgCep( "<?= __('Please check the CEP, the format looks invalid for us!') ?>" );
        }
    }

    <?php /* ajax para estimar valor do frete e prazo */ ?>
    function calcep( cep ) {
        document.cookie = "cep-correios="+cep+"; -1"; //limpa cookie
        var urlAjax = location.href; var validarUrl = /^https:\/\//;
        if ( urlAjax.match( validarUrl ) ) {
            urlAjax = '<?php echo Mage::getBaseUrl("link", true)."cepvalues/ajax" ?>';
        } else {
            urlAjax = '<?php echo $this->getUrl("cepvalues/ajax") ?>';
        }

        new Ajax.Request( urlAjax, {
            method: 'POST',
            parameters: {
                cepModes: '<?php echo $_cepModes; ?>',
                cepDestino: cep,
                cepOrigem: '<?php echo $_cepOrigin; ?>',
                cepPeso: '<?php echo $_proWeight; ?>',
                cepEmpresa: '<?php echo $_cepEmpresa; ?>',
                cepCodigo: '<?php echo $_cepPass; ?>',
                cepComprimento: '<?php echo $_cepComprimento; ?>',
                cepDiametro: '<?php echo $_cepDiametro; ?>',
                cepAltura: '<?php echo $_cepAltura; ?>',
                cepLargura: '<?php echo $_cepLargura; ?>',
                cepFormato: '<?php echo $_cepFormato; ?>'
            },
            evalScripts: true,
            onLoading: function() {
                showMsgCep( "<?= __('Please wait, searching CEP...') ?>" );
                //$('res_frete').update('<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif');?>" /> <span style="color: #888;"><?php echo $this->__('Loading...') ?></span>');
            },
            onSuccess: function(transport) {
                var res   = transport.responseText.evalJSON();
                var saida = "";

                <?php /* se foi configurado para exibir frete gratis */ ?>
                <?php if ( $_cepFree ) { if ( $_proPrice > $_cepFreePrice ) { ?>
                saida = '<p><span class="tipo"><?php echo __('FREE'); ?></span> <span class="prazo"><?php echo $_cepFreeDays; ?> <?= __('day(s)') ?></span> <span class="valor"><?= __('R$ 0,00') ?></span></p>';
                <?php } } ?>

                try {
                    for (var i in res) {
                        if (res.hasOwnProperty(i)) {
                            if ( 200 === res[i].status ) {
                                saida += '<p><span class="tipo">'+res[i].tipo+'</span> <span class="prazo">'+res[i].prazo+' <?= __('day(s)') ?></span> <span class="valor"><?= __('R$') ?> '+res[i].valor+'</span></p>';
                            } else {
                                saida += '<p>'+res[i].tipo+": "+res[i].msg+'</p>';
                            }
                        }
                    }
                } catch(e) {
                    //console.log( "<?= __('Ajax CalCep -Success- Error:') ?>"+e.message );
                    saida = e.message;
                }
                showMsgCep( saida );
            },
            onFailure: function() { 
                //console.log( "<?= __('Ajax CalCep Error: ...') ?>" );
                showMsgCep( errorThrown );
            },
            onComplete: function() { /*console.log( "<?= __('Ajax CalCep Complete') ?>" );*/ }
        });
    }

    <?php /* sempre que o campo cep perder o foco */ ?>
    $('cep').observe('blur', function () {
        var cep = $("cep").value;
        <?php /* se o campo cep foi preenchido */ ?>
        if (cep !== "") {
            beforeCalcep( cep );
        } else {
            showMsgCep( "<?= __('Sorry! No input, no valid response to you.') ?>" );
        }
    });

    <?php /* sempre que clicar no botao de estimar frete */ ?>
    $('cep-button').observe('click', function () {
        var cep = $("cep").value;
        <?php /* se o campo cep foi preenchido */ ?>
        if (cep !== "") {
            beforeCalcep( cep );
        } else {
            showMsgCep( "<?= __('Sorry! No input, no valid response to you.') ?>" );
        }
    });

    <?php /* se pegou um cookie na sessao, chama calculo de frete automaticamente */ ?>
    if ( $('cep').value === '' ) {
        $('cep').value = '<?php echo $this->getCookieManager(); ?>';
        <?php /* dispara evento de checagem automaticamente */ ?>
        if ($('cep').value !== "") { beforeCalcep( $('cep').value); }
    }

    <?php echo $this->getJsCustomCalculateCep(); ?>
});
//]]>
</script>

<?php /* HTLM displays  */ ?>
<div id="calc_cep">
    <p>
        <label><?= __('Estimate Shipping:') ?> </label>
        <span class="in_cep"><input type="text" name="cep" id="cep" min="5" max="9"></span>
        <button type="button" title="<?= __('>>') ?>" class="button" id="cep-button"><span><?= __('>>') ?></span></button>
    </p>
    <div id="res_frete" class="ocultar"><span class="loader"></span><?= __('Please wait, searching CEP...') ?></div> 
</div>

<?php } /* getProductType */ ?>
<?php } /* getEnabled */ ?>